# Generated by Django 3.1.5 on 2021-01-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=500)),
                ('desired_price', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flipkart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(max_length=500)),
                ('desired_price', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
