# Generated by Django 3.1.5 on 2021-01-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTracker', '0002_ebay_flipkart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='URL',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='ebay',
            name='URL',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='flipkart',
            name='URL',
            field=models.URLField(max_length=10000),
        ),
    ]
